apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.3.6
        ports:
        - containerPort: 3000
        env:
          - name: GF_INSTALL_PLUGINS
            value: "grafana-kubernetes-app"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: "Admin"
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  selector:
    app: grafana
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - host: grafana-k3smaster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-service
          servicePort: http
  - host: grafana.k3smaster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-service
          servicePort: http
