---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red:1.0.2-10
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: nodered
spec:
  selector:
    app: nodered
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 1880
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodered-ingress
spec:
  rules:
  - host: nodered-k3smaster.local
    http:
      paths:
      - backend:
          serviceName: nodered
          servicePort: 80
  - host: nodered.k3smaster.local
    http:
      paths:
      - backend:
          serviceName: nodered
          servicePort: 80
